export * from './Hero/Hero';
export * from './AboutSchool/AboutSchool';
export * from './Courses/Courses';
export * from './AboutMeSection/AboutMeSection';
export * from './FormatSection/FormatSection';
export * from './ForWhomSection/ForWhomSection';
export * from './Comments/Comments';
export * from './FreeClass/FreeClass';
export * from './CoursePageList/CoursePageList';
